# Generated by Django 5.1.5 on 2025-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('optin', models.BooleanField(default=False)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
