# Generated by Django 5.1.5 on 2025-02-09 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('artiste', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('realisateur', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('auteur', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
    ]
